apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      log_format my_format '... host: $host, http_host: $http_host ...';
      access_log /var/log/nginx/access.log my_format;
  
      server {
        listen 80;

        location /products {
          proxy_pass http://pms-app-service:9000/pms/products;
        }
        
        location /addProduct {
          proxy_pass http://pms-app-service:9000/pms/addProduct;
        }

        location /productById/ {
            proxy_pass http://pms-app-service:9000/pms/productById/;
        }

        location /product/ {
            proxy_pass http://pms-app-service:9000/pms/product/;
        }

        location /update {
            proxy_pass http://pms-app-service:9000/pms/update;
        }

        location /delete/ {
            proxy_pass http://pms-app-service:9000/pms/delete/;
        }
        location / {
          proxy_pass http://pms-app-service:9000;
          proxy_redirect http://pms-app-service:9000/ http://$http_host/;
        }
      }
    }
