apiVersion: v1
kind: Service
metadata:
  name: nginx-api-gateway
spec:
  type: NodePort
  selector:
    app: nginx-api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30090
