apiVersion: apps/v1
kind: Deployment
metadata:
  name: pas-deployment
  labels:
    app: pas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pas-app
  template:
    metadata:
      labels:
        app: pas-app
    spec:
      containers:
        - name: pas-app-container
          image: neeharikasingh/product-admin-service:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: pas-app-configmap
                  key: db-url 
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pas-app-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pas-app-secret
                  key: db-password
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: pas-app-configmap
                  key: rabbitmq_host 
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: pas-app-configmap
                  key: rabbitmq_port
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pas-app-secret
                  key: rabbitmq_username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pas-app-secret
                  key: rabbitmq_password